set -g status off
set -g pane-border-status top
set -g pane-border-format "#{pane_title}"
set -g pane-border-style fg=colour243
set -g pane-active-border-style fg=colour243
set -g default-terminal "tmux-256color"
set -g allow-rename off
set -g set-titles off
set -g mouse off
set -g escape-time 0
